services:
  - type: web
    name: stt-tool
    env: node
    plan: standard
    buildCommand: npm ci --production=false && npx prisma generate && npx prisma migrate deploy && npm run build && npm prune --production
    startCommand: npm run start
    autoDeploy: false
    envVars:
      - key: NODE_VERSION
        value: 18.20.3  # Use Node 18 LTS
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: stt-pg
          property: connectionString

databases:
  - name: stt-pg
    plan: standard
